"""Building the ``proprietary-files.txt`` blob list.

The output follows the format ``extract-utils`` expects: one path per line,
relative to the partition root for ``system`` blobs and prefixed with the
partition name for everything else.
"""

from __future__ import annotations

import fnmatch
from dataclasses import dataclass
from typing import Dict, Iterable, List, Tuple

from qcomdtgen.dump import AndroidDump, Partition

#: Directories inside a partition that can hold proprietary blobs.
_BLOB_DIRS: Tuple[str, ...] = (
    "app",
    "bin",
    "etc",
    "firmware",
    "framework",
    "lib",
    "lib64",
    "lib/rfsa",
    "overlay",
    "priv-app",
)

#: Extensions that are always shipped as blobs when found in a blob directory.
_BLOB_SUFFIXES: Tuple[str, ...] = (".so", ".apk", ".jar", ".bin", ".mbn", ".mdt", ".b00")

#: Paths never worth extracting - they are built from source or are noise.
_EXCLUDE_PATTERNS: Tuple[str, ...] = (
    "*/build.prop",
    "*.prop",
    "*.rc",
    "*.te",
    "*.sha256",
    "*.txt",
    "*.log",
    "*.dex",
    "*.vdex",
    "*.odex",
    "*.art",
    "*.oat",
    "etc/selinux/*",
    "etc/init/*",
    "etc/fstab*",
    "etc/passwd*",
    "etc/group*",
    "etc/NOTICE*",
    "etc/security/*",
    "lost+found/*",
    "*/oat/*",
    "apex/*",
)

#: System blobs are mostly built from source, so only a narrow allow list is
#: pulled from the system-side partitions.
_SYSTEM_INCLUDE_PATTERNS: Tuple[str, ...] = (
    "bin/*",
    "lib/lib*qti*.so",
    "lib/lib*qcom*.so",
    "lib/vendor.qti.*.so",
    "lib64/lib*qti*.so",
    "lib64/lib*qcom*.so",
    "lib64/vendor.qti.*.so",
    "lib/libgame*.so",
    "lib64/libgame*.so",
    "etc/permissions/*qti*.xml",
    "etc/permissions/*qualcomm*.xml",
    "etc/permissions/*com.qti*.xml",
    "framework/*qti*.jar",
    "framework/*qcom*.jar",
    "priv-app/*",
    "app/*",
)

_SYSTEM_SIDE_PARTITIONS: Tuple[str, ...] = ("system", "system_ext", "product")

#: Section header -> substrings that place a blob under it.  Order matters:
#: the first section whose keyword matches wins.
_SECTIONS: Tuple[Tuple[str, Tuple[str, ...]], ...] = (
    ("Firmware", ("firmware", "/fw/", ".mbn", ".mdt", ".b00")),
    ("Audio", ("audio", "sound", "acdb", "tfa", "cirrus", "aac", "adsp", "dolby")),
    ("Bluetooth", ("bluetooth", "bt_", "btlinux", "libbt")),
    ("Camera", ("camera", "camx", "chi", "ois", "eeprom", "imx", "s5k")),
    ("CNE / DPM", ("cne", "dpm", "vendor.qti.data", "dataservice")),
    ("Display", ("display", "sdm", "gralloc", "hwcomposer", "colorservice", "memtrack")),
    ("DRM", ("drm", "widevine", "playready", "oemcrypto")),
    ("Fingerprint", ("fingerprint", "goodix", "fpc", "egis", "biometric")),
    ("GPS", ("gnss", "gps", "location", "izat", "loc_", "xtra", "garden")),
    ("Graphics", ("adreno", "gpu", "vulkan", "opengl", "egl", "llvm")),
    ("IMS / Radio", ("ims", "radio", "ril", "qcrilnr", "qti-telephony", "telephony", "modem")),
    ("Media", ("media", "omx", "codec2", "c2", "venus", "vpp", "stagefright")),
    ("NFC", ("nfc", "nq-nci", "secure_element", "ese")),
    ("Perf", ("perf", "thermal", "boost", "power")),
    ("Sensors", ("sensor", "ssc", "slpi", "sns")),
    ("WiFi", ("wifi", "wlan", "cnss", "hostapd", "wpa_supplicant")),
    ("Keymaster / Gatekeeper", ("keymaster", "keymint", "gatekeeper", "qseecom", "spu", "trustedui")),
    ("USB", ("usb", "typec")),
    ("Misc", ()),
)


@dataclass
class BlobList:
    """The result of scanning a dump for proprietary blobs."""

    #: Section name -> sorted blob paths as written to proprietary-files.txt.
    sections: Dict[str, List[str]]

    @property
    def count(self) -> int:
        return sum(len(paths) for paths in self.sections.values())

    def render(self, dump: AndroidDump) -> str:
        """Render the list in ``extract-utils`` format."""
        lines = [
            f"# Unpinned blobs from {dump.fingerprint}",
            f"# Generated by qcomdtgen for {dump.vendor}/{dump.device}",
            "",
        ]
        for section, paths in self.sections.items():
            if not paths:
                continue
            lines.append(f"# {section}")
            lines.extend(paths)
            lines.append("")
        return "\n".join(lines).rstrip("\n") + "\n"


def _matches_any(path: str, patterns: Iterable[str]) -> bool:
    return any(fnmatch.fnmatch(path, pattern) for pattern in patterns)


def _is_blob(relative: str) -> bool:
    """Whether a partition-relative path looks like a shippable blob."""
    if not relative.startswith(_BLOB_DIRS):
        return False
    if _matches_any(relative, _EXCLUDE_PATTERNS):
        return False
    if relative.endswith(_BLOB_SUFFIXES):
        return True
    # Executables under bin/ and data files under etc/ carry no useful suffix.
    return relative.startswith(("bin/", "etc/", "firmware/"))


def _entry_path(partition: Partition, relative: str) -> str:
    """Path as written in proprietary-files.txt for this partition."""
    if partition.name == "system":
        return relative
    return f"{partition.name}/{relative}"


def _section_for(entry: str) -> str:
    lowered = entry.lower()
    for section, keywords in _SECTIONS:
        if any(keyword in lowered for keyword in keywords):
            return section
    return "Misc"


def collect_blobs(dump: AndroidDump) -> BlobList:
    """Scan every partition of ``dump`` and group the blobs into sections."""
    sections: Dict[str, List[str]] = {name: [] for name, _ in _SECTIONS}

    for name, partition in dump.partitions.items():
        system_side = name in _SYSTEM_SIDE_PARTITIONS
        for relative_path in partition.walk_files():
            relative = relative_path.as_posix()
            if not _is_blob(relative):
                continue
            if system_side and not _matches_any(relative, _SYSTEM_INCLUDE_PATTERNS):
                continue
            entry = _entry_path(partition, relative)
            sections[_section_for(entry)].append(entry)

    for paths in sections.values():
        paths.sort()
    return BlobList(sections=sections)
